// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.distributed;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string words = 1;</code>
   * @return A list containing the words.
   */
  java.util.List<java.lang.String>
      getWordsList();
  /**
   * <code>repeated string words = 1;</code>
   * @return The count of words.
   */
  int getWordsCount();
  /**
   * <code>repeated string words = 1;</code>
   * @param index The index of the element to return.
   * @return The words at the given index.
   */
  java.lang.String getWords(int index);
  /**
   * <code>repeated string words = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the words at the given index.
   */
  com.google.protobuf.ByteString
      getWordsBytes(int index);

  /**
   * <code>int32 senderId = 2;</code>
   * @return The senderId.
   */
  int getSenderId();

  /**
   * <code>repeated int32 vectorClock = 3;</code>
   * @return A list containing the vectorClock.
   */
  java.util.List<java.lang.Integer> getVectorClockList();
  /**
   * <code>repeated int32 vectorClock = 3;</code>
   * @return The count of vectorClock.
   */
  int getVectorClockCount();
  /**
   * <code>repeated int32 vectorClock = 3;</code>
   * @param index The index of the element to return.
   * @return The vectorClock at the given index.
   */
  int getVectorClock(int index);
}
