// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.distributed;

/**
 * Protobuf type {@code Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    vectorClock_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              words_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            words_.add(s);
            break;
          }
          case 16: {

            senderId_ = input.readInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              vectorClock_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            vectorClock_.addInt(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              vectorClock_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              vectorClock_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        words_ = words_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        vectorClock_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.distributed.MessageOuterClass.internal_static_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.distributed.MessageOuterClass.internal_static_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.distributed.Message.class, com.distributed.Message.Builder.class);
  }

  public static final int WORDS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList words_;
  /**
   * <code>repeated string words = 1;</code>
   * @return A list containing the words.
   */
  public com.google.protobuf.ProtocolStringList
      getWordsList() {
    return words_;
  }
  /**
   * <code>repeated string words = 1;</code>
   * @return The count of words.
   */
  public int getWordsCount() {
    return words_.size();
  }
  /**
   * <code>repeated string words = 1;</code>
   * @param index The index of the element to return.
   * @return The words at the given index.
   */
  public java.lang.String getWords(int index) {
    return words_.get(index);
  }
  /**
   * <code>repeated string words = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the words at the given index.
   */
  public com.google.protobuf.ByteString
      getWordsBytes(int index) {
    return words_.getByteString(index);
  }

  public static final int SENDERID_FIELD_NUMBER = 2;
  private int senderId_;
  /**
   * <code>int32 senderId = 2;</code>
   * @return The senderId.
   */
  public int getSenderId() {
    return senderId_;
  }

  public static final int VECTORCLOCK_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList vectorClock_;
  /**
   * <code>repeated int32 vectorClock = 3;</code>
   * @return A list containing the vectorClock.
   */
  public java.util.List<java.lang.Integer>
      getVectorClockList() {
    return vectorClock_;
  }
  /**
   * <code>repeated int32 vectorClock = 3;</code>
   * @return The count of vectorClock.
   */
  public int getVectorClockCount() {
    return vectorClock_.size();
  }
  /**
   * <code>repeated int32 vectorClock = 3;</code>
   * @param index The index of the element to return.
   * @return The vectorClock at the given index.
   */
  public int getVectorClock(int index) {
    return vectorClock_.getInt(index);
  }
  private int vectorClockMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < words_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, words_.getRaw(i));
    }
    if (senderId_ != 0) {
      output.writeInt32(2, senderId_);
    }
    if (getVectorClockList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(vectorClockMemoizedSerializedSize);
    }
    for (int i = 0; i < vectorClock_.size(); i++) {
      output.writeInt32NoTag(vectorClock_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < words_.size(); i++) {
        dataSize += computeStringSizeNoTag(words_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getWordsList().size();
    }
    if (senderId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, senderId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < vectorClock_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(vectorClock_.getInt(i));
      }
      size += dataSize;
      if (!getVectorClockList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      vectorClockMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.distributed.Message)) {
      return super.equals(obj);
    }
    com.distributed.Message other = (com.distributed.Message) obj;

    if (!getWordsList()
        .equals(other.getWordsList())) return false;
    if (getSenderId()
        != other.getSenderId()) return false;
    if (!getVectorClockList()
        .equals(other.getVectorClockList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWordsCount() > 0) {
      hash = (37 * hash) + WORDS_FIELD_NUMBER;
      hash = (53 * hash) + getWordsList().hashCode();
    }
    hash = (37 * hash) + SENDERID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderId();
    if (getVectorClockCount() > 0) {
      hash = (37 * hash) + VECTORCLOCK_FIELD_NUMBER;
      hash = (53 * hash) + getVectorClockList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.distributed.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distributed.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distributed.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distributed.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distributed.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distributed.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distributed.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distributed.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.distributed.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.distributed.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.distributed.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distributed.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.distributed.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Message)
      com.distributed.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.distributed.MessageOuterClass.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.distributed.MessageOuterClass.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.distributed.Message.class, com.distributed.Message.Builder.class);
    }

    // Construct using com.distributed.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      senderId_ = 0;

      vectorClock_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.distributed.MessageOuterClass.internal_static_Message_descriptor;
    }

    @java.lang.Override
    public com.distributed.Message getDefaultInstanceForType() {
      return com.distributed.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.distributed.Message build() {
      com.distributed.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.distributed.Message buildPartial() {
      com.distributed.Message result = new com.distributed.Message(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        words_ = words_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.words_ = words_;
      result.senderId_ = senderId_;
      if (((bitField0_ & 0x00000002) != 0)) {
        vectorClock_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.vectorClock_ = vectorClock_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.distributed.Message) {
        return mergeFrom((com.distributed.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.distributed.Message other) {
      if (other == com.distributed.Message.getDefaultInstance()) return this;
      if (!other.words_.isEmpty()) {
        if (words_.isEmpty()) {
          words_ = other.words_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureWordsIsMutable();
          words_.addAll(other.words_);
        }
        onChanged();
      }
      if (other.getSenderId() != 0) {
        setSenderId(other.getSenderId());
      }
      if (!other.vectorClock_.isEmpty()) {
        if (vectorClock_.isEmpty()) {
          vectorClock_ = other.vectorClock_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureVectorClockIsMutable();
          vectorClock_.addAll(other.vectorClock_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.distributed.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.distributed.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureWordsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        words_ = new com.google.protobuf.LazyStringArrayList(words_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string words = 1;</code>
     * @return A list containing the words.
     */
    public com.google.protobuf.ProtocolStringList
        getWordsList() {
      return words_.getUnmodifiableView();
    }
    /**
     * <code>repeated string words = 1;</code>
     * @return The count of words.
     */
    public int getWordsCount() {
      return words_.size();
    }
    /**
     * <code>repeated string words = 1;</code>
     * @param index The index of the element to return.
     * @return The words at the given index.
     */
    public java.lang.String getWords(int index) {
      return words_.get(index);
    }
    /**
     * <code>repeated string words = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the words at the given index.
     */
    public com.google.protobuf.ByteString
        getWordsBytes(int index) {
      return words_.getByteString(index);
    }
    /**
     * <code>repeated string words = 1;</code>
     * @param index The index to set the value at.
     * @param value The words to set.
     * @return This builder for chaining.
     */
    public Builder setWords(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsIsMutable();
      words_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string words = 1;</code>
     * @param value The words to add.
     * @return This builder for chaining.
     */
    public Builder addWords(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureWordsIsMutable();
      words_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string words = 1;</code>
     * @param values The words to add.
     * @return This builder for chaining.
     */
    public Builder addAllWords(
        java.lang.Iterable<java.lang.String> values) {
      ensureWordsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, words_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string words = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWords() {
      words_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string words = 1;</code>
     * @param value The bytes of the words to add.
     * @return This builder for chaining.
     */
    public Builder addWordsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureWordsIsMutable();
      words_.add(value);
      onChanged();
      return this;
    }

    private int senderId_ ;
    /**
     * <code>int32 senderId = 2;</code>
     * @return The senderId.
     */
    public int getSenderId() {
      return senderId_;
    }
    /**
     * <code>int32 senderId = 2;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(int value) {
      
      senderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 senderId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      
      senderId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList vectorClock_ = emptyIntList();
    private void ensureVectorClockIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        vectorClock_ = mutableCopy(vectorClock_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 vectorClock = 3;</code>
     * @return A list containing the vectorClock.
     */
    public java.util.List<java.lang.Integer>
        getVectorClockList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(vectorClock_) : vectorClock_;
    }
    /**
     * <code>repeated int32 vectorClock = 3;</code>
     * @return The count of vectorClock.
     */
    public int getVectorClockCount() {
      return vectorClock_.size();
    }
    /**
     * <code>repeated int32 vectorClock = 3;</code>
     * @param index The index of the element to return.
     * @return The vectorClock at the given index.
     */
    public int getVectorClock(int index) {
      return vectorClock_.getInt(index);
    }
    /**
     * <code>repeated int32 vectorClock = 3;</code>
     * @param index The index to set the value at.
     * @param value The vectorClock to set.
     * @return This builder for chaining.
     */
    public Builder setVectorClock(
        int index, int value) {
      ensureVectorClockIsMutable();
      vectorClock_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 vectorClock = 3;</code>
     * @param value The vectorClock to add.
     * @return This builder for chaining.
     */
    public Builder addVectorClock(int value) {
      ensureVectorClockIsMutable();
      vectorClock_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 vectorClock = 3;</code>
     * @param values The vectorClock to add.
     * @return This builder for chaining.
     */
    public Builder addAllVectorClock(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureVectorClockIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, vectorClock_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 vectorClock = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVectorClock() {
      vectorClock_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Message)
  }

  // @@protoc_insertion_point(class_scope:Message)
  private static final com.distributed.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.distributed.Message();
  }

  public static com.distributed.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.distributed.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

