// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.distributed;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string processedWords = 1;</code>
   * @return A list containing the processedWords.
   */
  java.util.List<java.lang.String>
      getProcessedWordsList();
  /**
   * <code>repeated string processedWords = 1;</code>
   * @return The count of processedWords.
   */
  int getProcessedWordsCount();
  /**
   * <code>repeated string processedWords = 1;</code>
   * @param index The index of the element to return.
   * @return The processedWords at the given index.
   */
  java.lang.String getProcessedWords(int index);
  /**
   * <code>repeated string processedWords = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the processedWords at the given index.
   */
  com.google.protobuf.ByteString
      getProcessedWordsBytes(int index);

  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @return A list containing the vectorClock.
   */
  java.util.List<java.lang.Integer> getVectorClockList();
  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @return The count of vectorClock.
   */
  int getVectorClockCount();
  /**
   * <code>repeated int32 vectorClock = 2;</code>
   * @param index The index of the element to return.
   * @return The vectorClock at the given index.
   */
  int getVectorClock(int index);
}
